name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Enable Corepack
        run: corepack enable
      - name: Install
        run: pnpm install --frozen-lockfile
      - name: Typecheck
        run: pnpm -w run typecheck
      - name: Lint
        run: pnpm -w run lint
      - name: Build
        run: pnpm -w run build
      - name: Test
        run: pnpm -w run test

